[package]
name = "film_informationen"
version = "0.1.0"
authors = ["TotorRuns <totoruns@protonmail.net>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
gtk = "0.9.2"
glib = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"

[[bin]]
name = "film_informationen"
path = "src/main.rs"
